// Auto-generated by scripts/gen_serve.js — do not edit manually
// Run: node scripts/gen_serve.js
import { apiClient } from "./client.js";

// === sportApi === 比赛报名
const sportApi = new apiClient();
sportApi._add_endpoint("register", "/sport/register", ["name","academicNumber","sportType","college","competitionId"], ["group"], "POST"); // 运动员报名
sportApi._add_endpoint("preview", "/sport/preview", ["token","gameId"], [], "POST"); // 预览报名信息
sportApi._add_endpoint("export", "/sport/export", ["token","gameId"], [], "POST"); // 导出报名信息
sportApi._add_endpoint("getGameList", "/sport/getGameList", [], [], "GET"); // 获取可报名比赛列表
sportApi._add_endpoint("getGameInfo", "/sport/getGameInfo", ["game"], [], "GET"); // 获取比赛信息

// === volunteerApi === 志愿者管理
const volunteerApi = new apiClient();
volunteerApi._add_endpoint("uploadData", "/api/volunteer/uploadData", ["type","token","id","gameId"], ["data"], "POST"); // 上传比赛数据
volunteerApi._add_endpoint("updateResult", "/api/volunteer/updateResult", [], ["token","gameId","time","program","marked","group","data"], "POST"); // 执行总裁更新结果
volunteerApi._add_endpoint("reviewResult", "/api/volunteer/reviewResult", [], ["token","gameId","time","program","marked","group"], "POST"); // 执行总裁审核结果
volunteerApi._add_endpoint("login", "/api/volunteer/login", [], ["name","position","studentNumber","road","gameId"], "POST"); // 志愿者登录
volunteerApi._add_endpoint("getCompetitionList", "/api/volunteer/getCompetitionList", [], ["token","gameId","time","marked"], "POST"); // 获取比赛列表
volunteerApi._add_endpoint("confirmResult", "/api/volunteer/confirmResult", [], ["token","gameId","time","program","marked","group"], "POST"); // 执行总裁确认结果

// === funVolunteerApi === fun-volunteer-controller
const funVolunteerApi = new apiClient();
funVolunteerApi._add_endpoint("uploadResult", "/api/funVolunteer/uploadResult", ["token","eventId","road","isValid"], ["dto","round","rawScore","invalidType","invalidReason"], "POST"); // 按道次录入成绩
funVolunteerApi._add_endpoint("reviewResults", "/api/funVolunteer/reviewResults", ["token","eventId"], ["dto","round"], "POST"); // 执行总裁查看成绩
funVolunteerApi._add_endpoint("login", "/api/funVolunteer/login", ["competitionId","name","studentNumber","password"], ["dto"], "POST"); // 登录
funVolunteerApi._add_endpoint("getEventList", "/api/funVolunteer/getEventList", ["token","competitionId"], ["dto","round"], "POST"); // 获取可录入项目列表
funVolunteerApi._add_endpoint("confirmResults", "/api/funVolunteer/confirmResults", ["token","eventId"], ["dto","round"], "POST"); // 执行总裁确认成绩
funVolunteerApi._add_endpoint("queryCompetition", "/api/funVolunteer/queryCompetition", ["studentNumber"], [], "GET"); // 根据学号查询志愿者参与活动列表

// === contractApi === 校友电子合同签署接口
const contractApi = new apiClient();
contractApi._add_endpoint("uploadSignature", "/api/contract/uploadSignature", ["token","signature","type"], [], "POST"); // 上传手写签名
contractApi._add_endpoint("uploadInfo", "/api/contract/uploadInfo", ["type"], [], "POST"); // 上传合同/同意书信息
contractApi._add_endpoint("isSignature", "/api/contract/isSignature", [], ["token"], "POST"); // 查询签名状态
contractApi._add_endpoint("getSignature", "/api/contract/getSignature", ["uuid","hash"], [], "POST"); // 获取签名图片
contractApi._add_endpoint("getContractResource", "/api/contract/getContractResource", ["type","token"], [], "POST"); // 获取合同资源
contractApi._add_endpoint("download", "/api/contract/download", ["type","token"], [], "POST"); // 下载合同PDF
contractApi._add_endpoint("template", "/api/contract/template", ["type"], [], "GET"); // 获取合同/同意书模板
contractApi._add_endpoint("check", "/api/contract/check", ["uuid","type","signature","id"], [], "GET"); // 校验合同有效性

// === alumnusApi === 优秀运动员管理
const alumnusApi = new apiClient();
alumnusApi._add_endpoint("updateInfo", "/alumnus/updateInfo", [], ["username","password","token"], "POST"); // 更新优秀运动员信息
alumnusApi._add_endpoint("login", "/alumnus/login", [], ["username","password","token"], "POST"); // 优秀运动员登录
alumnusApi._add_endpoint("discuss", "/alumnus/discuss", ["token","discussionAlumnusId"], ["content"], "POST"); // 发表评论
alumnusApi._add_endpoint("getDiscussionList", "/alumnus/getDiscussionList", ["id"], ["page","limit"], "GET"); // 获取评论列表
alumnusApi._add_endpoint("getAlumnusList", "/alumnus/getAlumnusList", [], ["page","limit"], "GET"); // 获取优秀运动员列表
alumnusApi._add_endpoint("getAlumnusDetail", "/alumnus/getAlumnusDetail", ["id"], [], "GET"); // 获取优秀运动员详情

// === adminApi === 管理员后台
const adminApi = new apiClient();
adminApi._add_endpoint("withdrawNews", "/admin/withdrawNews", ["id","token"], [], "POST"); // 恢复删除新闻
adminApi._add_endpoint("uploadVolunteer", "/admin/uploadVolunteer", [], ["token","gameId","data"], "POST"); // 添加比赛志愿者
adminApi._add_endpoint("uploadVideo", "/admin/uploadVideo", ["uploadVideoVo"], [], "POST"); // 上传新闻视频
adminApi._add_endpoint("uploadNews", "/admin/uploadNews", [], ["token","title","content"], "POST"); // 发布新闻
adminApi._add_endpoint("uploadImage", "/admin/uploadImage", ["vo"], [], "POST"); // 上传新闻图片
adminApi._add_endpoint("updatePublishTime", "/admin/updatePublishTime", ["token","newsId"], ["publishTime"], "POST"); // 更新新闻发布时间
adminApi._add_endpoint("updateAdmin", "/admin/updateAdmin", ["token","id","adminName","password"], [], "POST"); // 更新管理员信息
adminApi._add_endpoint("postSignUpList", "/admin/postSignUpList", ["token","athleteList","activityTypes","athleteActivityLimits","competitionName","endTime"], ["colleges","collegeActivityLimits","sameActivityMaxLimit","leaderPhone","startTime"], "POST"); // 发布比赛报名
adminApi._add_endpoint("login", "/admin/login", [], ["loginType","userName","password","ip"], "POST"); // 管理员登录
adminApi._add_endpoint("getParticipatAthleteList", "/admin/getParticipatAthleteList", [], ["token","gameId","event","group"], "POST"); // 获取参赛运动员列表
adminApi._add_endpoint("getAlumnusSignatureStatus", "/admin/getAlumnusSignatureStatus", [], ["token","page","limit"], "POST"); // 获取校友签名情况
adminApi._add_endpoint("getAdminList", "/admin/getAdminList", ["token"], [], "POST"); // 获取管理员列表
adminApi._add_endpoint("deleteNews", "/admin/deleteNews", ["id","token"], [], "POST"); // 删除新闻
adminApi._add_endpoint("deleteLeader", "/admin/deleteLeader", ["id","token"], [], "POST"); // 删除领导
adminApi._add_endpoint("deleteAlumnus", "/admin/deleteAlumnus", ["id","token"], [], "POST"); // 删除优秀运动员
adminApi._add_endpoint("deleteAdmin", "/admin/deleteAdmin", ["token","adminId"], [], "POST"); // 删除管理员
adminApi._add_endpoint("confirmSignUp", "/admin/confirmSignUp", [], ["token","gameId"], "POST"); // 确认比赛报名
adminApi._add_endpoint("arrangeProgram", "/admin/arrangeProgram", [], ["token","gameId","event","date","time","marked","group","data"], "POST"); // 安排比赛日程
adminApi._add_endpoint("addLeader", "/admin/addLeader", ["token"], ["name","age","introduction","position","imgUrl"], "POST"); // 添加领导
adminApi._add_endpoint("addAlumnus", "/admin/addAlumnus", ["token"], ["name","age","grade","introduction","whetherInSchool","password","imgUrl","id"], "POST"); // 添加优秀运动员
adminApi._add_endpoint("addAdmin", "/admin/addAdmin", ["token","adminName","password"], [], "POST"); // 添加管理员

// === adminFunApi === 趣味运动会管理员相关接口
const adminFunApi = new apiClient();
adminFunApi._add_endpoint("updateVolunteer", "/admin/fun/updateVolunteer", ["token","volunteerId"], ["dto","name","studentNumber","position","password","road"], "POST"); // 更新志愿者
adminFunApi._add_endpoint("updateTeam", "/admin/fun/updateTeam", ["token","college"], ["dto","competitionId","eventId","teamId","teamName","members","id"], "POST"); // 更新参赛队伍
adminFunApi._add_endpoint("updateRoad", "/admin/fun/updateRoad", ["token","eventId"], ["dto","teamRoads"], "POST"); // 更新道次分配
adminFunApi._add_endpoint("updateResult", "/admin/fun/updateResult", ["token","resultId","rawScore","isValid"], ["dto","invalidType","invalidReason"], "POST"); // 管理员修改成绩
adminFunApi._add_endpoint("updateGame", "/admin/fun/updateGame", [], ["dto","token","gameName","startTime","endTime","status","competitionId"], "POST"); // 更新活动
adminFunApi._add_endpoint("updateEvent", "/admin/fun/updateEvent", ["token","competitionId","eventName","rules","unit","sortDirection","sortOrder"], ["dto","id","eventId"], "POST"); // 更新比赛单项
adminFunApi._add_endpoint("importVolunteers", "/admin/fun/importVolunteers", ["token","competitionId"], ["dto","volunteers"], "POST"); // 志愿者管理
adminFunApi._add_endpoint("getVolunteerList", "/admin/fun/getVolunteerList", ["token","competitionId"], ["dto"], "POST"); // 获取志愿者列表
adminFunApi._add_endpoint("getTeamList", "/admin/fun/getTeamList", ["token","eventId"], ["dto"], "POST"); // 获取参赛队伍列表
adminFunApi._add_endpoint("getResults", "/admin/fun/getResults", ["token","eventId"], ["dto"], "POST"); // 管理员管理成绩
adminFunApi._add_endpoint("getGameList", "/admin/fun/getGameList", [], ["dto","token","page","size"], "POST"); // 获取活动列表
adminFunApi._add_endpoint("getEventList", "/admin/fun/getEventList", ["token","competitionId"], ["dto"], "POST"); // 获取比赛单项列表
adminFunApi._add_endpoint("deleteVolunteer", "/admin/fun/deleteVolunteer", ["token","volunteerId"], ["dto"], "POST"); // 删除志愿者
adminFunApi._add_endpoint("deleteTeam", "/admin/fun/deleteTeam", ["token","teamId"], ["dto"], "POST"); // 删除参赛队伍
adminFunApi._add_endpoint("deleteGame", "/admin/fun/deleteGame", [], ["dto","token","competitionId"], "POST"); // 删除活动
adminFunApi._add_endpoint("deleteEvent", "/admin/fun/deleteEvent", ["token","eventId"], ["dto"], "POST"); // 删除比赛单项
adminFunApi._add_endpoint("createVolunteer", "/admin/fun/createVolunteer", ["token","competitionId","name","studentNumber","position","password","road"], ["dto"], "POST"); // 新增志愿者
adminFunApi._add_endpoint("createTeam", "/admin/fun/createTeam", ["token","college"], ["dto","competitionId","eventId","teamId","teamName","members","id"], "POST"); // 录入参赛队伍
adminFunApi._add_endpoint("createGame", "/admin/fun/createGame", [], ["dto","token","gameName","startTime","endTime","status","competitionId"], "POST"); // 创建活动
adminFunApi._add_endpoint("createEvent", "/admin/fun/createEvent", ["token","competitionId","eventName","rules","unit","sortDirection","sortOrder"], ["dto","id","eventId"], "POST"); // 创建比赛单项
adminFunApi._add_endpoint("assignRoad", "/admin/fun/assignRoad", ["token","eventId"], ["dto","teamRoads"], "POST"); // 道次分配

// === activityApi === 新闻活动
const activityApi = new apiClient();
activityApi._add_endpoint("getNewsList", "/activity/getNewsList", [], ["page","limit"], "GET"); // 获取新闻列表
activityApi._add_endpoint("getNewsList_2", "/activity/getNewsList", ["token"], ["page","limit"], "POST"); // 获取新闻列表(管理员)
activityApi._add_endpoint("getVideo", "/activity/getVideo", ["uuid","type"], [], "GET"); // 获取视频
activityApi._add_endpoint("getNewsDetail", "/activity/getNewsDetail", ["id"], [], "GET"); // 获取新闻详情
activityApi._add_endpoint("getImage", "/activity/getImage", ["uuid","type"], [], "GET"); // 获取图片

// === registerApi === 报名辅助
const registerApi = new apiClient();
registerApi._add_endpoint("getCollegeDetail", "/register/getCollegeDetail", [], [], "GET"); // 获取学院列表

// === leaderApi === 领导信息
const leaderApi = new apiClient();
leaderApi._add_endpoint("getLeaderList", "/leader/getLeaderList", [], [], "GET"); // 获取领导列表
leaderApi._add_endpoint("getLeaderDetail", "/leader/getLeaderDetail", ["id"], [], "GET"); // 获取领导详情

// === athleteApi === 运动员认证
const athleteApi = new apiClient();
athleteApi._add_endpoint("login", "/athlete/login", [], [], "GET"); // 运动员登录
athleteApi._add_endpoint("getSessionId", "/athlete/getSessionId", ["code","s"], [], "GET"); // 获取SessionId

// === funGameApi === fun-public-controller
const funGameApi = new apiClient();
funGameApi._add_endpoint("getGameList", "/api/funGame/list", [], ["page","size"], "GET"); // 公众查询活动列表
funGameApi._add_endpoint("getTotalPoints", "/api/funGame/getTotalPoints", ["competitionId"], [], "GET"); // 公众查询总积分排名
funGameApi._add_endpoint("getEventResults", "/api/funGame/getEventResults", ["competitionId","eventId"], ["round"], "GET"); // 公众查询单项成绩
funGameApi._add_endpoint("getFoulReason", "/api/funGame/foulReason", [], [], "GET"); // 公众查询犯规枚举
funGameApi._add_endpoint("getGameDetail", "/api/funGame/detail", ["competitionId"], [], "GET"); // 公众查询活动详情

// === competitionApi === 比赛信息查询接口
const competitionApi = new apiClient();
competitionApi._add_endpoint("result", "/api/competition/result", ["competitionId","time","program","marked","group"], [], "GET"); // 查询比赛结果
competitionApi._add_endpoint("queryCompetition", "/api/competition/queryCompetition", ["studentNumber"], [], "GET"); // 根据志愿者学号获取比赛列表
competitionApi._add_endpoint("list", "/api/competition/list", [], ["page","size"], "GET"); // 分页获取比赛列表
competitionApi._add_endpoint("getGameSchedule", "/api/competition/getGameSchedule", ["id"], [], "GET"); // 获取比赛日程
competitionApi._add_endpoint("getCompetitionList", "/api/competition/getCompetitionList", [], [], "GET"); // 获取全部比赛列表

export { sportApi, volunteerApi, funVolunteerApi, contractApi, alumnusApi, adminApi, adminFunApi, activityApi, registerApi, leaderApi, athleteApi, funGameApi, competitionApi };
