import fs from "node:fs/promises";

function resolveSchema(openApiData, schema) {
  if (!schema) return null;
  if (schema.$ref) {
    const parts = schema.$ref.replace("#/", "").split("/");
    let resolved = openApiData;
    for (const part of parts) {
      resolved = resolved?.[part];
    }
    return resolveSchema(openApiData, resolved);
  }
  if (schema.allOf) {
    const merged = { properties: {}, required: [] };
    for (const sub of schema.allOf) {
      const resolved = resolveSchema(openApiData, sub);
      if (resolved?.properties)
        Object.assign(merged.properties, resolved.properties);
      if (resolved?.required) merged.required.push(...resolved.required);
    }
    return merged;
  }
  return schema;
}

function deriveApiName(paths) {
  const segments = paths.map((p) => p.split("/").filter(Boolean));
  const prefixes = segments.map((s) => s.slice(0, -1));
  let commonLength = 0;
  for (let i = 0; i < prefixes[0].length; i++) {
    if (prefixes.every((s) => s[i] === prefixes[0][i])) {
      commonLength++;
    } else {
      break;
    }
  }
  let common = prefixes[0].slice(0, commonLength);
  if (common[0] === "api") common = common.slice(1);
  return (
    common
      .map((seg, i) =>
        i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1),
      )
      .join("") + "Api"
  );
}

function pathToFuncName(path) {
  return path
    .replace(/^\//, "")
    .split("/")
    .map((seg, i) =>
      i === 0 ? seg : seg.charAt(0).toUpperCase() + seg.slice(1),
    )
    .join("")
    .replace(/-/g, "_");
}

async function generateServe() {
  try {
    const envContent = await fs.readFile(".env", "utf8");
    const match = envContent.match(/^backend=(.*)$/m);
    if (!match || !match[1]) {
      console.error("Could not find backend in .env");
      process.exit(1);
    }
    const backendUrl = match[1].trim();
    const openApiUrl = `${backendUrl}/v3/api-docs`;

    console.log(`Fetching OpenAPI data from ${openApiUrl}...`);
    const response = await fetch(openApiUrl);
    if (!response.ok) {
      throw new Error(`Failed to fetch OpenAPI JSON: ${response.statusText}`);
    }
    const openApiData = await response.json();

    const httpMethods = ["get", "post", "put", "delete", "patch"];
    const tagGroups = {};

    for (const path in openApiData.paths) {
      for (const method of httpMethods) {
        const op = openApiData.paths[path][method];
        if (!op) continue;

        const tag = op.tags?.[0] || "default";
        if (!tagGroups[tag]) tagGroups[tag] = [];

        let funcName =
          op.operationId
            ?.replace(/Using(GET|POST|PUT|DELETE|PATCH)$/i, "")
            .replace(/_\d+$/, "") || pathToFuncName(path);

        const queryParams = [];
        const bodyRequired = [];
        const bodyOptional = [];

        if (op.parameters) {
          for (const p of op.parameters) {
            if (p.in === "query") {
              queryParams.push({ name: p.name, required: !!p.required });
            }
          }
        }

        const bodySchema = resolveSchema(
          openApiData,
          op.requestBody?.content?.["application/json"]?.schema,
        );
        if (bodySchema?.properties) {
          const requiredSet = new Set(bodySchema.required || []);
          for (const name of Object.keys(bodySchema.properties)) {
            if (requiredSet.has(name)) {
              bodyRequired.push(name);
            } else {
              bodyOptional.push(name);
            }
          }
        }

        const allRequired = [
          ...queryParams.filter((p) => p.required).map((p) => p.name),
          ...bodyRequired,
        ];
        const allOptional = [
          ...queryParams.filter((p) => !p.required).map((p) => p.name),
          ...bodyOptional,
        ];

        tagGroups[tag].push({
          funcName,
          path,
          method: method.toUpperCase(),
          allRequired,
          allOptional,
          summary: op.summary || "",
        });
      }
    }

    const lines = [];
    lines.push(
      "// Auto-generated by scripts/gen_serve.js — do not edit manually",
    );
    lines.push("// Run: node scripts/gen_serve.js");
    lines.push('import { apiClient } from "./client.js";');
    lines.push("");

    const apiNames = [];
    for (const [tag, eps] of Object.entries(tagGroups)) {
      const apiName = deriveApiName(eps.map((e) => e.path));
      apiNames.push(apiName);
      lines.push(`// === ${apiName} === ${tag}`);
      lines.push(`const ${apiName} = new apiClient();`);

      const totalNameCount = {};
      for (const ep of eps) {
        totalNameCount[apiName] = totalNameCount[apiName] || {};
        const nameCount = totalNameCount[apiName];
        let name = ep.funcName;
        if (nameCount[name]) {
          nameCount[name]++;
          name += "_" + nameCount[name];
          console.log(
            `Warning: Duplicate function name "${ep.funcName}" in ${apiName}, renamed to "${name}"`,
          );
          console.log(nameCount);
        } else {
          nameCount[name] = 1;
        }
        const comment = ep.summary ? ` // ${ep.summary}` : "";
        if (name.includes("1")) {
          console.log(
            `Warning: Function name "${name}" in ${apiName} may be a duplicate.`,
          );
        }
        lines.push(
          `${apiName}._add_endpoint("${name}", "${ep.path}", ${JSON.stringify(ep.allRequired)}, ${JSON.stringify(ep.allOptional)}, "${ep.method}");${comment}`,
        );
      }
      lines.push("");
    }

    lines.push(`export { ${apiNames.join(", ")} };`);
    lines.push("");

    await fs.writeFile("src/api/serve.js", lines.join("\n"), "utf8");
    console.log("Successfully generated src/api/serve.js");
    console.log(
      `Generated ${apiNames.length} API clients: ${apiNames.join(", ")}`,
    );
  } catch (error) {
    console.error("Error generating serve.js:", error);
    process.exit(1);
  }
}

generateServe();
